export enum PRODUCT_TYPE {
  SELL = 'SELL',
  GIVE = 'GIVE',
}

export enum PAYMENT_METHOD {
  PAYPAL = 'PAYPAL',
  VNPAY = 'VNPAY',
  MOMO = 'MOMO',
  CASH = 'CASH',
}

export enum BILL_STATUS {
  NEW = 'NEW',
  CONFIRMED = 'CONFIRMED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUND = 'REFUND',
  BACK = 'BACK',
}

export enum BILL_STATUS_NOTIFICATION {
  REFUND_USER = 'REFUND_USER',
  REFUND_SELLER = 'REFUND_SELLER',
  CONFIRMED_REFUND = 'CONFIRMED_REFUND',
  BACK_USER = 'BACK_USER',
  BACK_SELLER = 'BACK_SELLER',
  CONFIRM_DELIVERED_BY_USER = 'CONFIRM_DELIVERED_BY_USER',
}
