export enum PRODUCT_TYPE {
  SELL = 'SELL',
  GIVE = 'GIVE',
}

export enum PAYMENT_METHOD {
  PAYPAL = 'PAYPAL',
  VNPAY = 'VNPAY',
  MOMO = 'MOMO',
  CASH = 'CASH',
}

export enum BILL_STATUS {
  NEW = 'NEW',
  CONFIRMED = 'CONFIRMED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUND = 'REFUND',
  BACK = 'BACK',
}
