export enum NotificationType {
  UPDATE_INFO = 'UPDATE_INFO',
  FOLLOW = 'FOLLOW',
  SENT_ADD_FRIEND = 'SENT_ADD_FRIEND',
  ACCEPTED_ADD_FRIEND_OF_SENDER = 'ACCEPTED_ADD_FRIEND_OF_SENDER',
  ACCEPTED_ADD_FRIEND_OF_RECEIVER = 'ACCEPTED_ADD_FRIEND_OF_RECEIVER',
  REJECT_ADD_FRIEND = 'REJECT_ADD_FRIEND',
  NEW_POST = 'NEW_POST',
  BILL = 'BILL',
  EVALUATION = 'EVALUATION',
  FEEDBACK = 'FEEDBACK',
  REPORT_FEEDBACK = 'REPORT_FEEDBACK',
}
