import { config } from 'dotenv';
config({ path: process.env.NODE_ENV === 'development' ? `.env.dev` : `.env.prod` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const NODE_ENV = process.env.NODE_ENV;
export const SALT_ROUNDS = Number(process.env.SALT_ROUNDS);
export const TAX_RATE = Number(process.env.TAX_RATE);
export const TAX_SHIPPING_RATE = Number(process.env.TAX_SHIPPING_RATE);

export const {
  URL_TRAIN,
  DATABASE_URL,
  PORT,
  ORIGIN,
  APP_SECRET,
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET,
  JWT_ACCESS_TOKEN_EXPIRES,
  JWT_REFRESH_TOKEN_EXPIRES,
  FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_DATABASE_URL,
  PAGE_DEFAULT,
  LIMIT_DEFAULT,
  MAIL_HOST,
  MAIL_USER,
  MAIL_PASSWORD,
  MAIL_FROM,
  EMAIL_ADMIN,
  PASSWORD_ADMIN,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET,
  VN_PAY_VERSION,
  VN_PAY_COMMAND,
  VN_PAY_CURRENCY_VND,
  VN_PAY_LOCALE_EN,
  VN_PAY_LOCALE_VN,
  VN_PAY_MERCHANT,
  VN_PAY_SECRET,
  VN_PAY_PAYMENT_URL,
  PAYPAL_CLIENT_ID,
  PAYPAL_CLIENT_SECRET,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_USERNAME,
  REDIS_PASSWORD,
  URL_FE,
  HOST,
  ELASTICSEARCH_NODE,
  ELASTICSEARCH_PRODUCTS_INDEX,
} = process.env;
