# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DTEX BE CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
         touch .env.prod
         echo "${{ secrets.ENV_FILE_PROD }}" > .env.prod

  deploy:
    runs-on: self-hosted
    needs: build
    env:
      APP_NAME: dtex-be
      PATH_TO_DOCKER_COMPOSE_FILE: ~/workspace/actions-runner-be/_work/DATN_BE/DATN_BE/
    steps:
    - run: |
        cd $PATH_TO_DOCKER_COMPOSE_FILE
        docker stop $APP_NAME || true
        docker rm $APP_NAME || true
        docker image rm $APP_NAME || true
        docker-compose up -d
        docker image prune -f
        
